name: qmix
n_agents: 2
lr: 0.0005
gamma: 0.99
batch_size: 1
buffer_size: 1000
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
target_update_interval: 200
action_selector: "epsilon_greedy"
evaluation_epsilon: 0.0
runner: "episode"
obs_agent_id: True
obs_last_action: False
obs_individual_obs: False
standardise_returns: False
standardise_rewards: False 
use_rnn: True
agent_output_type: default
learner: "q_learner"
mixer: "qmix"
mixing_embed_dim: 32
use_cuda: True
cuda_device: 0
double_q: True
target_update_interval_or_tau: 200  # Interval for updating target networks
t_max: 1