env: cooking
env_args:
  num_agents: 2
  episode_limit: 2000
  level: "coop_test"
  meta_file: "example"
  recipes: ["TomatoLettuceSalad", "CarrotBanana"]
  obs_spaces: ["feature_vector", "feature_vector"]
  agent_visualization: ["human", "robot"]
  action_scheme: "scheme1"
  end_condition_all_dishes: True
  render: True
  reward_scheme:
    recipe_reward: 1000
    max_time_penalty: 0
    recipe_penalty: -40
    recipe_node_reward: 100
  key: "cooking_key"